---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pgsql-db
spec:
  selector:
    matchLabels:
      app: pgsql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgsql-db
    spec:
      containers:
      - image: postgres:10.13
        name: pgsql
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgres/data
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: newdb
        - name: POSTGRES_USER 
          value: testuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: pass
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 90m
            memory: 72Mi
          requests:
            cpu: 74m
            memory: 45Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: int-storage
