---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-with-net-tools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nt
  template:
    metadata:
      labels:
        app: nginx-nt
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 80m
            memory: 64Mi
          requests:
            cpu: 64m
            memory: 32Mi
        readinessProbe: 
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          periodSeconds: 25
          successThreshold: 1
          timeoutSeconds: 60
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
